// Database type definitions for ZimEstimate
// This file will be auto-generated by Supabase CLI after schema setup

export type Json =
    | string
    | number
    | boolean
    | null
    | { [key: string]: Json | undefined }
    | Json[];

export type MilestoneType =
    | 'substructure'
    | 'superstructure'
    | 'roofing'
    | 'finishing'
    | 'exterior';

export type AccessLevel = 'view' | 'collaborate';

export type Currency = 'USD' | 'ZWG';

export interface Database {
    public: {
        Tables: {
            users: {
                Row: {
                    id: string;
                    email: string;
                    name: string | null;
                    preferred_currency: Currency;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    email: string;
                    name?: string | null;
                    preferred_currency?: Currency;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    email?: string;
                    name?: string | null;
                    preferred_currency?: Currency;
                    created_at?: string;
                };
            };
            projects: {
                Row: {
                    id: string;
                    owner_id: string;
                    name: string;
                    location: string | null;
                    status: string;
                    created_at: string;
                    updated_at: string;
                };
                Insert: {
                    id?: string;
                    owner_id: string;
                    name: string;
                    location?: string | null;
                    status?: string;
                    created_at?: string;
                    updated_at?: string;
                };
                Update: {
                    id?: string;
                    owner_id?: string;
                    name?: string;
                    location?: string | null;
                    status?: string;
                    created_at?: string;
                    updated_at?: string;
                };
            };
            milestones: {
                Row: {
                    id: string;
                    project_id: string;
                    type: MilestoneType;
                    calculated_progress: number;
                    manual_override: boolean;
                    override_value: number | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    project_id: string;
                    type: MilestoneType;
                    calculated_progress?: number;
                    manual_override?: boolean;
                    override_value?: number | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    project_id?: string;
                    type?: MilestoneType;
                    calculated_progress?: number;
                    manual_override?: boolean;
                    override_value?: number | null;
                    created_at?: string;
                };
            };
            project_shares: {
                Row: {
                    id: string;
                    project_id: string;
                    shared_with_email: string;
                    access_level: AccessLevel;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    project_id: string;
                    shared_with_email: string;
                    access_level?: AccessLevel;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    project_id?: string;
                    shared_with_email?: string;
                    access_level?: AccessLevel;
                    created_at?: string;
                };
            };
            materials: {
                Row: {
                    id: string;
                    category: string;
                    name: string;
                    unit: string;
                    price_usd: number;
                    price_zwg: number;
                    supplier_id: string | null;
                    last_updated: string;
                };
                Insert: {
                    id?: string;
                    category: string;
                    name: string;
                    unit: string;
                    price_usd: number;
                    price_zwg: number;
                    supplier_id?: string | null;
                    last_updated?: string;
                };
                Update: {
                    id?: string;
                    category?: string;
                    name?: string;
                    unit?: string;
                    price_usd?: number;
                    price_zwg?: number;
                    supplier_id?: string | null;
                    last_updated?: string;
                };
            };
            estimate_items: {
                Row: {
                    id: string;
                    project_id: string;
                    milestone_id: string;
                    material_id: string;
                    quantity_budgeted: number;
                    quantity_actual: number;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    project_id: string;
                    milestone_id: string;
                    material_id: string;
                    quantity_budgeted: number;
                    quantity_actual?: number;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    project_id?: string;
                    milestone_id?: string;
                    material_id?: string;
                    quantity_budgeted?: number;
                    quantity_actual?: number;
                    created_at?: string;
                };
            };
            exchange_rates: {
                Row: {
                    id: string;
                    date: string;
                    usd_to_zwg: number;
                    source: string;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    date: string;
                    usd_to_zwg: number;
                    source: string;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    date?: string;
                    usd_to_zwg?: number;
                    source?: string;
                    created_at?: string;
                };
            };
            suppliers: {
                Row: {
                    id: string;
                    name: string;
                    website: string | null;
                    is_trusted: boolean;
                    scrape_config: Json | null;
                    created_at: string;
                };
                Insert: {
                    id?: string;
                    name: string;
                    website?: string | null;
                    is_trusted?: boolean;
                    scrape_config?: Json | null;
                    created_at?: string;
                };
                Update: {
                    id?: string;
                    name?: string;
                    website?: string | null;
                    is_trusted?: boolean;
                    scrape_config?: Json | null;
                    created_at?: string;
                };
            };
        };
    };
}
