import type { ProjectUtilityConfig } from '@/lib/database.types';

export const DEFAULT_UTILITY_CONFIG: ProjectUtilityConfig = {
  id: '',
  project_id: '',
  solar_enabled: false,
  solar_system_type: 'hybrid',
  solar_daily_usage: 'moderate',
  solar_appliances: ['lights', 'fridge'],
  solar_roof_type: 'tile',
  water_enabled: false,
  water_source: 'municipal',
  borehole_exists: false,
  borehole_depth_m: 40,
  pump_type: 'submersible',
  tank_count: 1,
  tank_size_litres: 5000,
  tank_stand_required: true,
  wastewater_enabled: false,
  sanitation_type: 'municipal',
  bathroom_count: 2,
  occupant_count: 5,
  septic_tank_type: 'brick',
  soakaway_type: 'stone_pit',
  rainwater_enabled: false,
  roof_area_m2: 150,
  rainwater_gutter_type: 'pvc',
  rainwater_tank_size_litres: 2500,
  rainwater_first_flush: true,
  rainwater_sand_filter: false,
  greywater_enabled: false,
  greywater_sources: ['shower'],
  greywater_use: 'garden',
  created_at: '',
  updated_at: '',
};
