-- ─── Quick BOQs Table ──────────────────────────────────────────────────────────
-- Stores BOQ results generated by the quick-projects wizard.
-- Can be standalone (user_id only) or linked to a project (project_id).

CREATE TABLE IF NOT EXISTS quick_boqs (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id    UUID REFERENCES projects(id) ON DELETE SET NULL,
  project_type  TEXT NOT NULL CHECK (project_type IN ('septic','solar','water','borehole','fencing','paving')),
  answers       JSONB NOT NULL DEFAULT '{}',
  boq_items     JSONB NOT NULL DEFAULT '[]',
  labor_method  TEXT CHECK (labor_method IN ('daily_rate','percentage')),
  labor_value   NUMERIC,            -- either rate/day or % (stored as integer, e.g. 25 = 25%)
  labor_days    INTEGER,            -- only used for daily_rate method
  labor_workers INTEGER DEFAULT 2, -- only used for daily_rate method
  labor_enabled BOOLEAN DEFAULT false,
  markup_pct    NUMERIC DEFAULT 0,
  currency      TEXT DEFAULT 'USD' CHECK (currency IN ('USD','ZWG')),
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ─── Row-Level Security ────────────────────────────────────────────────────────

ALTER TABLE quick_boqs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own quick BOQs"
  ON quick_boqs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own quick BOQs"
  ON quick_boqs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own quick BOQs"
  ON quick_boqs FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own quick BOQs"
  ON quick_boqs FOR DELETE
  USING (auth.uid() = user_id);

-- ─── Indexes ──────────────────────────────────────────────────────────────────

CREATE INDEX quick_boqs_user_id_idx       ON quick_boqs (user_id);
CREATE INDEX quick_boqs_project_id_idx    ON quick_boqs (project_id) WHERE project_id IS NOT NULL;
CREATE INDEX quick_boqs_project_type_idx  ON quick_boqs (project_type);

-- ─── Auto-update updated_at ───────────────────────────────────────────────────

CREATE TRIGGER update_quick_boqs_updated_at
  BEFORE UPDATE ON quick_boqs
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();
