'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import MainLayout from '@/components/layout/MainLayout';
import Card, { CardBadge } from '@/components/ui/Card';
import Button from '@/components/ui/Button';
import Input from '@/components/ui/Input';
import {
    FileArrowUp,
    PencilSimple,
    Camera,
    ArrowRight,
    ArrowLeft,
    MapPin,
    Buildings,
} from '@phosphor-icons/react';

type BOQMethod = 'upload' | 'manual' | 'photo' | null;

interface ProjectFormData {
    name: string;
    location: string;
    type: string;
    boqMethod: BOQMethod;
}

const projectTypes = [
    { value: 'residential', label: 'Residential House' },
    { value: 'commercial', label: 'Commercial Building' },
    { value: 'renovation', label: 'Renovation' },
    { value: 'extension', label: 'Extension' },
];

export default function NewProject() {
    const router = useRouter();
    const [step, setStep] = useState(1);
    const [formData, setFormData] = useState<ProjectFormData>({
        name: '',
        location: '',
        type: 'residential',
        boqMethod: null,
    });

    const handleInputChange = (field: keyof ProjectFormData, value: string) => {
        setFormData((prev) => ({ ...prev, [field]: value }));
    };

    const handleMethodSelect = (method: BOQMethod) => {
        setFormData((prev) => ({ ...prev, boqMethod: method }));
    };

    const handleContinue = () => {
        if (step === 1 && formData.name && formData.location) {
            setStep(2);
        } else if (step === 2 && formData.boqMethod) {
            // Create project and redirect
            const projectId = 'demo-project-1'; // Would be generated by Supabase
            router.push(`/projects/${projectId}`);
        }
    };

    const canContinue = step === 1
        ? formData.name && formData.location
        : formData.boqMethod !== null;

    return (
        <MainLayout title="New Project">
            <div className="new-project">
                {/* Progress Steps */}
                <div className="steps-indicator">
                    <div className={`step ${step >= 1 ? 'active' : ''}`}>
                        <span className="step-number">1</span>
                        <span className="step-label">Project Details</span>
                    </div>
                    <div className="step-line" />
                    <div className={`step ${step >= 2 ? 'active' : ''}`}>
                        <span className="step-number">2</span>
                        <span className="step-label">BOQ Method</span>
                    </div>
                    <div className="step-line" />
                    <div className={`step ${step >= 3 ? 'active' : ''}`}>
                        <span className="step-number">3</span>
                        <span className="step-label">Configure</span>
                    </div>
                </div>

                {/* Step 1: Project Details */}
                {step === 1 && (
                    <div className="step-content">
                        <div className="step-header">
                            <h2>Project Details</h2>
                            <p>Enter the basic information about your construction project</p>
                        </div>

                        <Card className="form-card">
                            <div className="form-grid">
                                <Input
                                    label="Project Name"
                                    placeholder="e.g., Borrowdale 4-Bed House"
                                    value={formData.name}
                                    onChange={(e) => handleInputChange('name', e.target.value)}
                                    icon={<Buildings size={18} weight="light" />}
                                />

                                <Input
                                    label="Location"
                                    placeholder="e.g., Harare, Zimbabwe"
                                    value={formData.location}
                                    onChange={(e) => handleInputChange('location', e.target.value)}
                                    icon={<MapPin size={18} weight="light" />}
                                />

                                <div className="select-wrapper">
                                    <label className="input-label">Project Type</label>
                                    <select
                                        value={formData.type}
                                        onChange={(e) => handleInputChange('type', e.target.value)}
                                        className="select-field"
                                    >
                                        {projectTypes.map((type) => (
                                            <option key={type.value} value={type.value}>
                                                {type.label}
                                            </option>
                                        ))}
                                    </select>
                                </div>
                            </div>
                        </Card>
                    </div>
                )}

                {/* Step 2: BOQ Method Selection */}
                {step === 2 && (
                    <div className="step-content">
                        <div className="step-header">
                            <h2>Smart BOQ Builder</h2>
                            <p>Choose how you want to create your Bill of Quantities</p>
                        </div>

                        <div className="boq-methods">
                            <Card
                                variant="choice"
                                selected={formData.boqMethod === 'upload'}
                                onClick={() => handleMethodSelect('upload')}
                            >
                                <div className="choice-icon">
                                    <FileArrowUp size={40} weight="light" />
                                </div>
                                <h4>Upload Floor Plan</h4>
                                <p>AI analyzes your blueprint to extract measurements</p>
                                <CardBadge variant="success">Best for Accuracy</CardBadge>
                            </Card>

                            <Card
                                variant="choice"
                                selected={formData.boqMethod === 'manual'}
                                onClick={() => handleMethodSelect('manual')}
                            >
                                <div className="choice-icon">
                                    <PencilSimple size={40} weight="light" />
                                </div>
                                <h4>Manual Entry</h4>
                                <p>Build your BOQ step by step with guided inputs</p>
                            </Card>

                            <Card
                                variant="choice"
                                selected={formData.boqMethod === 'photo'}
                                onClick={() => handleMethodSelect('photo')}
                            >
                                <div className="choice-icon">
                                    <Camera size={40} weight="light" />
                                </div>
                                <h4>Photo Quote</h4>
                                <p>Scan a handwritten quote from hardware store</p>
                                <CardBadge variant="accent">OCR Powered</CardBadge>
                            </Card>
                        </div>
                    </div>
                )}

                {/* Navigation */}
                <div className="step-navigation">
                    {step > 1 && (
                        <Button
                            variant="secondary"
                            icon={<ArrowLeft size={18} weight="bold" />}
                            onClick={() => setStep(step - 1)}
                        >
                            Back
                        </Button>
                    )}
                    <div className="nav-spacer" />
                    <Button
                        icon={<ArrowRight size={18} weight="bold" />}
                        iconPosition="right"
                        onClick={handleContinue}
                        disabled={!canContinue}
                    >
                        {step === 2 ? 'Create Project' : 'Continue'}
                    </Button>
                </div>
            </div>

            <style jsx>{`
        .new-project {
          max-width: 800px;
          margin: 0 auto;
        }

        .steps-indicator {
          display: flex;
          align-items: center;
          justify-content: center;
          gap: var(--spacing-md);
          margin-bottom: var(--spacing-2xl);
        }

        .step {
          display: flex;
          align-items: center;
          gap: var(--spacing-sm);
          color: var(--color-text-muted);
        }

        .step.active {
          color: var(--color-primary);
        }

        .step-number {
          width: 32px;
          height: 32px;
          border-radius: 50%;
          background: var(--color-border-light);
          display: flex;
          align-items: center;
          justify-content: center;
          font-weight: 600;
          font-size: 0.875rem;
        }

        .step.active .step-number {
          background: var(--color-accent);
          color: var(--color-primary);
        }

        .step-label {
          font-size: 0.875rem;
          font-weight: 500;
        }

        .step-line {
          width: 60px;
          height: 2px;
          background: var(--color-border-light);
        }

        .step-content {
          margin-bottom: var(--spacing-xl);
        }

        .step-header {
          text-align: center;
          margin-bottom: var(--spacing-xl);
        }

        .step-header h2 {
          font-size: 1.5rem;
          font-weight: 600;
          color: var(--color-text);
          margin: 0 0 var(--spacing-xs) 0;
        }

        .step-header p {
          color: var(--color-text-secondary);
          margin: 0;
        }

        .form-grid {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-lg);
        }

        .select-wrapper {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-xs);
        }

        .input-label {
          font-size: 0.875rem;
          font-weight: 500;
          color: var(--color-text);
        }

        .select-field {
          width: 100%;
          padding: 0.75rem 1rem;
          font-size: 0.9375rem;
          font-family: inherit;
          border: 1px solid var(--color-border);
          border-radius: var(--radius-md);
          background: var(--color-surface);
          color: var(--color-text);
          cursor: pointer;
        }

        .select-field:focus {
          outline: none;
          border-color: var(--color-accent);
          box-shadow: 0 0 0 3px rgba(252, 163, 17, 0.15);
        }

        .boq-methods {
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          gap: var(--spacing-lg);
        }

        .choice-icon {
          width: 72px;
          height: 72px;
          border-radius: 50%;
          background: var(--color-background);
          display: flex;
          align-items: center;
          justify-content: center;
          color: var(--color-accent);
          margin-bottom: var(--spacing-sm);
        }

        .boq-methods h4 {
          font-size: 1rem;
          font-weight: 600;
          color: var(--color-text);
          margin: 0 0 var(--spacing-xs) 0;
        }

        .boq-methods p {
          font-size: 0.875rem;
          color: var(--color-text-secondary);
          margin: 0 0 var(--spacing-sm) 0;
        }

        .step-navigation {
          display: flex;
          align-items: center;
          padding-top: var(--spacing-lg);
          border-top: 1px solid var(--color-border-light);
        }

        .nav-spacer {
          flex: 1;
        }

        @media (max-width: 768px) {
          .boq-methods {
            grid-template-columns: 1fr;
          }

          .step-label {
            display: none;
          }
        }
      `}</style>
        </MainLayout>
    );
}
